spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/cinedb?serverTimezone=UTC
    username: root
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: ecommerce-backend
server:
  port: 8080